### PR TITLE
Connect to db

### PR DESCRIPTION
**Pull request by Xaffels**
Pulling connect_to_db to master.

### CODE REVIEW

**Review by JDrakeFord — APPROVED** [review]
Looks good

**Comment by Ben-Coco** [comment]
looks good

**Review by JDrakeFord — APPROVED** [review]
looks even better the 2nd time

**Review by Ben-Coco — COMMENTED** [review]
there we go

**Review by Ben-Coco — APPROVED** [review]

**Comment by Ben-Coco** [comment]
hallelujah

**Pull request merged**
